file_object = open("test.txt","r+")
print("Current Position:",file_object.tell())
print(file_object.read(5))
print("After read 5 bytes Position:",file_object.tell())
file_object.seek(2,1)
print("After moving to 3rd Position:",file_object.tell())
print(file_object.read())
print("After read Position:",file_object.tell())
file_object.seek(5,0)
print("Current Position:",file_object.tell())